spring.application.name=oAuth
spring.security.oauth2.client.registration.google.client-id=8312667941-68vmcsq12rqr5fidqeptuvnlmp7cp1do.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google
server.port=8081
# Session management properties
server.servlet.session.timeout=5m